# Generated by Django 2.2.4 on 2020-03-16 10:06

import django.core.files.storage
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='private', location='/Users/pierrelavalley/repos/eat-until-api/private'), upload_to='avatars', verbose_name='avatar'),
        ),
    ]
