# Generated by Django 2.2.4 on 2020-05-15 08:12

import django.core.files.storage
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200504_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url='private',
                    location='/Users/tominardi/workspace/eat-until-api/private'
                ),
                upload_to='avatars',
                verbose_name='avatar'),
        ),
    ]
