# Generated by Django 2.2.4 on 2020-04-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean13',
            field=models.CharField(blank=True, max_length=13, verbose_name='Code-barre ean13'),
        ),
    ]
