# Generated by Django 2.2.4 on 2020-05-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_product_ean13'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notification_date',
            field=models.DateField(editable=False, null=True, verbose_name='notification date'),
        ),
    ]
